package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "sifc_dev")
public class Cliente implements java.io.Serializable {

	private Integer cliId;
	private Tipodocumento tipodocumento;
	private String cliDocumento;
	private String cliNombre;
	private String cliDireccion;
	private int cliTelefono;
	private String cliCorreo;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Cliente() {
		
	}

	public Cliente(Tipodocumento tipodocumento, String cliDocumento, String cliNombre, String cliDireccion,
			int cliTelefono) {
		this.tipodocumento = tipodocumento;
		this.cliDocumento = cliDocumento;
		this.cliNombre = cliNombre;
		this.cliDireccion = cliDireccion;
		this.cliTelefono = cliTelefono;
	}

	public Cliente(Tipodocumento tipodocumento, String cliDocumento, String cliNombre, String cliDireccion,
			int cliTelefono, String cliCorreo, Set<Pedido> pedidos) {
		this.tipodocumento = tipodocumento;
		this.cliDocumento = cliDocumento;
		this.cliNombre = cliNombre;
		this.cliDireccion = cliDireccion;
		this.cliTelefono = cliTelefono;
		this.cliCorreo = cliCorreo;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cliId", unique = true, nullable = false)
	public Integer getCliId() {
		return this.cliId;
	}

	public void setCliId(Integer cliId) {
		this.cliId = cliId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cliTipoDocumento_tdId", nullable = false)
	public Tipodocumento getTipodocumento() {
		return this.tipodocumento;
	}

	public void setTipodocumento(Tipodocumento tipodocumento) {
		this.tipodocumento = tipodocumento;
	}

	@Column(name = "cliDocumento", nullable = false, length = 90)
	public String getCliDocumento() {
		return this.cliDocumento;
	}

	public void setCliDocumento(String cliDocumento) {
		this.cliDocumento = cliDocumento;
	}

	@Column(name = "cliNombre", nullable = false, length = 180)
	public String getCliNombre() {
		return this.cliNombre;
	}

	public void setCliNombre(String cliNombre) {
		this.cliNombre = cliNombre;
	}

	@Column(name = "cliDireccion", nullable = false, length = 90)
	public String getCliDireccion() {
		return this.cliDireccion;
	}

	public void setCliDireccion(String cliDireccion) {
		this.cliDireccion = cliDireccion;
	}

	@Column(name = "cliTelefono", nullable = false)
	public int getCliTelefono() {
		return this.cliTelefono;
	}

	public void setCliTelefono(int cliTelefono) {
		this.cliTelefono = cliTelefono;
	}

	@Column(name = "cliCorreo", length = 180)
	public String getCliCorreo() {
		return this.cliCorreo;
	}

	public void setCliCorreo(String cliCorreo) {
		this.cliCorreo = cliCorreo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
