package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComposicionId generated by hbm2java
 */
@Embeddable
public class ComposicionId implements java.io.Serializable {

	private int cmpFormaFarmaceuticaProId;
	private int cmpMateriaPrimaMpId;

	public ComposicionId() {
	}

	public ComposicionId(int cmpFormaFarmaceuticaProId, int cmpMateriaPrimaMpId) {
		this.cmpFormaFarmaceuticaProId = cmpFormaFarmaceuticaProId;
		this.cmpMateriaPrimaMpId = cmpMateriaPrimaMpId;
	}

	@Column(name = "cmpFormaFarmaceutica_proId", nullable = false)
	public int getCmpFormaFarmaceuticaProId() {
		return this.cmpFormaFarmaceuticaProId;
	}

	public void setCmpFormaFarmaceuticaProId(int cmpFormaFarmaceuticaProId) {
		this.cmpFormaFarmaceuticaProId = cmpFormaFarmaceuticaProId;
	}

	@Column(name = "cmpMateriaPrima_mpId", nullable = false)
	public int getCmpMateriaPrimaMpId() {
		return this.cmpMateriaPrimaMpId;
	}

	public void setCmpMateriaPrimaMpId(int cmpMateriaPrimaMpId) {
		this.cmpMateriaPrimaMpId = cmpMateriaPrimaMpId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComposicionId))
			return false;
		ComposicionId castOther = (ComposicionId) other;

		return (this.getCmpFormaFarmaceuticaProId() == castOther.getCmpFormaFarmaceuticaProId())
				&& (this.getCmpMateriaPrimaMpId() == castOther.getCmpMateriaPrimaMpId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCmpFormaFarmaceuticaProId();
		result = 37 * result + this.getCmpMateriaPrimaMpId();
		return result;
	}

}
