package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Envase generated by hbm2java
 */
@Entity
@Table(name = "envase", catalog = "sifc_dev")
public class Envase implements java.io.Serializable {

	private Integer envId;
	private Proveedor proveedor;
	private String envIdentificacionProducto;
	private String envComposicion;
	private String envCondicionConservacion;
	private int envCapacidad;
	private Set<Imagenporenvase> imagenporenvases = new HashSet<Imagenporenvase>(0);
	private Set<Protocoloelaboracion> protocoloelaboracions = new HashSet<Protocoloelaboracion>(0);
	private Set<Loteenvase> loteenvases = new HashSet<Loteenvase>(0);

	public Envase() {
	}

	public Envase(Proveedor proveedor, String envIdentificacionProducto, String envComposicion,
			String envCondicionConservacion, int envCapacidad) {
		this.proveedor = proveedor;
		this.envIdentificacionProducto = envIdentificacionProducto;
		this.envComposicion = envComposicion;
		this.envCondicionConservacion = envCondicionConservacion;
		this.envCapacidad = envCapacidad;
	}

	public Envase(Proveedor proveedor, String envIdentificacionProducto, String envComposicion,
			String envCondicionConservacion, int envCapacidad, Set<Imagenporenvase> imagenporenvases,
			Set<Protocoloelaboracion> protocoloelaboracions, Set<Loteenvase> loteenvases) {
		this.proveedor = proveedor;
		this.envIdentificacionProducto = envIdentificacionProducto;
		this.envComposicion = envComposicion;
		this.envCondicionConservacion = envCondicionConservacion;
		this.envCapacidad = envCapacidad;
		this.imagenporenvases = imagenporenvases;
		this.protocoloelaboracions = protocoloelaboracions;
		this.loteenvases = loteenvases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "envId", unique = true, nullable = false)
	public Integer getEnvId() {
		return this.envId;
	}

	public void setEnvId(Integer envId) {
		this.envId = envId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "envProveedor_prvId", nullable = false)
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@Column(name = "envIdentificacionProducto", nullable = false, length = 65535)
	public String getEnvIdentificacionProducto() {
		return this.envIdentificacionProducto;
	}

	public void setEnvIdentificacionProducto(String envIdentificacionProducto) {
		this.envIdentificacionProducto = envIdentificacionProducto;
	}

	@Column(name = "envComposicion", nullable = false, length = 65535)
	public String getEnvComposicion() {
		return this.envComposicion;
	}

	public void setEnvComposicion(String envComposicion) {
		this.envComposicion = envComposicion;
	}

	@Column(name = "envCondicionConservacion", nullable = false, length = 65535)
	public String getEnvCondicionConservacion() {
		return this.envCondicionConservacion;
	}

	public void setEnvCondicionConservacion(String envCondicionConservacion) {
		this.envCondicionConservacion = envCondicionConservacion;
	}

	@Column(name = "envCapacidad", nullable = false)
	public int getEnvCapacidad() {
		return this.envCapacidad;
	}

	public void setEnvCapacidad(int envCapacidad) {
		this.envCapacidad = envCapacidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "envase")
	public Set<Imagenporenvase> getImagenporenvases() {
		return this.imagenporenvases;
	}

	public void setImagenporenvases(Set<Imagenporenvase> imagenporenvases) {
		this.imagenporenvases = imagenporenvases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "envase")
	public Set<Protocoloelaboracion> getProtocoloelaboracions() {
		return this.protocoloelaboracions;
	}

	public void setProtocoloelaboracions(Set<Protocoloelaboracion> protocoloelaboracions) {
		this.protocoloelaboracions = protocoloelaboracions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "envase")
	public Set<Loteenvase> getLoteenvases() {
		return this.loteenvases;
	}

	public void setLoteenvases(Set<Loteenvase> loteenvases) {
		this.loteenvases = loteenvases;
	}

}
