package com.duopharma.models;
// Generated 25/02/2020 04:47:30 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Estanteria generated by hbm2java
 */
@Entity
@Table(name = "estanteria", catalog = "sifc_dev")
public class Estanteria implements java.io.Serializable {

	private Integer estId;
	private Bodega bodega;
	private int estCodigo;
	private int estCapacidad;
	private int estCapacidadOcupada;
	private String estEstado;
	private Producto producto;
	private Materiaprima materiaprima;
	//private Integer estProductoProId;
	//private Integer estMateriaPrimaMpId;
	private String estHumedad;
	private String estTemperatura;
	
	@Transient
	private Integer proId;
	
	@Transient
	private Integer boId;
	
	@Transient
	private Integer mpId;

	public Estanteria() {
	}

	public Estanteria(Bodega bodega, int estCodigo, int estCapacidad, int estCapacidadOcupada, String estEstado,
			String estHumedad, String estTemperatura) {
		this.bodega = bodega;
		this.estCodigo = estCodigo;
		this.estCapacidad = estCapacidad;
		this.estCapacidadOcupada = estCapacidadOcupada;
		this.estEstado = estEstado;
		this.estHumedad = estHumedad;
		this.estTemperatura = estTemperatura;
	}
	
	@Transient
	public Integer getProId() {
		return proId;
	}

	@Transient
	public void setProId(Integer proId) {
		this.proId = proId;
	}

	@Transient
	public Integer getBoId() {
		return boId;
	}
	
	@Transient
	public void setBoId(Integer boId) {
		this.boId = boId;
	}
	
	@Transient
	public Integer getMpId() {
		return mpId;
	}

	@Transient
	public void setMpId(Integer mpId) {
		this.mpId = mpId;
	}

	public Estanteria(Bodega bodega, int estCodigo, int estCapacidad, int estCapacidadOcupada, String estEstado,
			Integer estProductoProId, Integer estMateriaPrimaMpId, String estHumedad, String estTemperatura) {
		this.bodega = bodega;
		this.estCodigo = estCodigo;
		this.estCapacidad = estCapacidad;
		this.estCapacidadOcupada = estCapacidadOcupada;
		this.estEstado = estEstado;
		this.estHumedad = estHumedad;
		this.estTemperatura = estTemperatura;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "estId", unique = true, nullable = false)
	public Integer getEstId() {
		return this.estId;
	}

	public void setEstId(Integer estId) {
		this.estId = estId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "estBodega_BoId", nullable = false)
	public Bodega getBodega() {
		return this.bodega;
	}

	public void setBodega(Bodega bodega) {
		this.bodega = bodega;
	}

	@Column(name = "estCodigo", nullable = false)
	public int getEstCodigo() {
		return this.estCodigo;
	}

	public void setEstCodigo(int estCodigo) {
		this.estCodigo = estCodigo;
	}

	@Column(name = "estCapacidad", nullable = false)
	public int getEstCapacidad() {
		return this.estCapacidad;
	}

	public void setEstCapacidad(int estCapacidad) {
		this.estCapacidad = estCapacidad;
	}

	@Column(name = "estCapacidadOcupada", nullable = false)
	public int getEstCapacidadOcupada() {
		return this.estCapacidadOcupada;
	}

	public void setEstCapacidadOcupada(int estCapacidadOcupada) {
		this.estCapacidadOcupada = estCapacidadOcupada;
	}

	@Column(name = "estEstado", nullable = false, length = 45)
	public String getEstEstado() {
		return this.estEstado;
	}

	public void setEstEstado(String estEstado) {
		this.estEstado = estEstado;
	}
	/*
	@Column(name = "estProducto_proId")
	public Integer getEstProductoProId() {
		return this.estProductoProId;
	}

	public void setEstProductoProId(Integer estProductoProId) {
		this.estProductoProId = estProductoProId;
	}*/
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "estProducto_proId", nullable = true)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}
	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "estMateriaPrima_mpId", nullable = true)
	public Materiaprima getMateriaprima() {
		return materiaprima;
	}

	public void setMateriaprima(Materiaprima materiaprima) {
		this.materiaprima = materiaprima;
	}

	@Column(name = "estHumedad", nullable = false, length = 20)
	public String getEstHumedad() {
		return this.estHumedad;
	}

	public void setEstHumedad(String estHumedad) {
		this.estHumedad = estHumedad;
	}

	@Column(name = "estTemperatura", nullable = false, length = 5)
	public String getEstTemperatura() {
		return this.estTemperatura;
	}

	public void setEstTemperatura(String estTemperatura) {
		this.estTemperatura = estTemperatura;
	}

}
