package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fichaanaliticamateria generated by hbm2java
 */
@Entity
@Table(name = "fichaanaliticamateria", catalog = "sifc_dev")
public class Fichaanaliticamateria implements java.io.Serializable {

	private Integer famId;
	private Loteenvase loteenvase;
	private Lotemateriaprima lotemateriaprima;
	private Usuario usuario;
	private String famNumeroFicha;
	private byte[] famFirmaAutorizacion;
	private Date famFechaAutorizacion;
	private String famDescripcionProcedimiento;
	private String famIdentificacion;
	private String famObservacion;

	public Fichaanaliticamateria() {
	}

	public Fichaanaliticamateria(Usuario usuario, String famNumeroFicha, byte[] famFirmaAutorizacion,
			Date famFechaAutorizacion, String famDescripcionProcedimiento, String famIdentificacion) {
		this.usuario = usuario;
		this.famNumeroFicha = famNumeroFicha;
		this.famFirmaAutorizacion = famFirmaAutorizacion;
		this.famFechaAutorizacion = famFechaAutorizacion;
		this.famDescripcionProcedimiento = famDescripcionProcedimiento;
		this.famIdentificacion = famIdentificacion;
	}

	public Fichaanaliticamateria(Loteenvase loteenvase, Lotemateriaprima lotemateriaprima, Usuario usuario,
			String famNumeroFicha, byte[] famFirmaAutorizacion, Date famFechaAutorizacion,
			String famDescripcionProcedimiento, String famIdentificacion, String famObservacion) {
		this.loteenvase = loteenvase;
		this.lotemateriaprima = lotemateriaprima;
		this.usuario = usuario;
		this.famNumeroFicha = famNumeroFicha;
		this.famFirmaAutorizacion = famFirmaAutorizacion;
		this.famFechaAutorizacion = famFechaAutorizacion;
		this.famDescripcionProcedimiento = famDescripcionProcedimiento;
		this.famIdentificacion = famIdentificacion;
		this.famObservacion = famObservacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "famId", unique = true, nullable = false)
	public Integer getFamId() {
		return this.famId;
	}

	public void setFamId(Integer famId) {
		this.famId = famId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "famLoteEnvase_lenId")
	public Loteenvase getLoteenvase() {
		return this.loteenvase;
	}

	public void setLoteenvase(Loteenvase loteenvase) {
		this.loteenvase = loteenvase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "famLoteMateriaPrima_lmpId")
	public Lotemateriaprima getLotemateriaprima() {
		return this.lotemateriaprima;
	}

	public void setLotemateriaprima(Lotemateriaprima lotemateriaprima) {
		this.lotemateriaprima = lotemateriaprima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "famAutorizador", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "famNumeroFicha", nullable = false, length = 45)
	public String getFamNumeroFicha() {
		return this.famNumeroFicha;
	}

	public void setFamNumeroFicha(String famNumeroFicha) {
		this.famNumeroFicha = famNumeroFicha;
	}

	@Column(name = "famFirmaAutorizacion", nullable = false)
	public byte[] getFamFirmaAutorizacion() {
		return this.famFirmaAutorizacion;
	}

	public void setFamFirmaAutorizacion(byte[] famFirmaAutorizacion) {
		this.famFirmaAutorizacion = famFirmaAutorizacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "famFechaAutorizacion", nullable = false, length = 10)
	public Date getFamFechaAutorizacion() {
		return this.famFechaAutorizacion;
	}

	public void setFamFechaAutorizacion(Date famFechaAutorizacion) {
		this.famFechaAutorizacion = famFechaAutorizacion;
	}

	@Column(name = "famDescripcionProcedimiento", nullable = false, length = 65535)
	public String getFamDescripcionProcedimiento() {
		return this.famDescripcionProcedimiento;
	}

	public void setFamDescripcionProcedimiento(String famDescripcionProcedimiento) {
		this.famDescripcionProcedimiento = famDescripcionProcedimiento;
	}

	@Column(name = "famIdentificacion", nullable = false, length = 65535)
	public String getFamIdentificacion() {
		return this.famIdentificacion;
	}

	public void setFamIdentificacion(String famIdentificacion) {
		this.famIdentificacion = famIdentificacion;
	}

	@Column(name = "famObservacion", length = 65535)
	public String getFamObservacion() {
		return this.famObservacion;
	}

	public void setFamObservacion(String famObservacion) {
		this.famObservacion = famObservacion;
	}

}
