package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Formafarmaceutica generated by hbm2java
 */
@Entity
@Table(name = "formafarmaceutica", catalog = "sifc_dev")
public class Formafarmaceutica implements java.io.Serializable {

	private int proId;
	private Producto producto;
	private String ffaViaAdministracion;
	private String ffaTipoForma;
	private Set<Composicion> composicions = new HashSet<Composicion>(0);
	private Set<Protocoloelaboracion> protocoloelaboracions = new HashSet<Protocoloelaboracion>(0);

	public Formafarmaceutica() {
	}

	public Formafarmaceutica(Producto producto, String ffaViaAdministracion, String ffaTipoForma) {
		this.producto = producto;
		this.ffaViaAdministracion = ffaViaAdministracion;
		this.ffaTipoForma = ffaTipoForma;
	}

	public Formafarmaceutica(Producto producto, String ffaViaAdministracion, String ffaTipoForma,
			Set<Composicion> composicions, Set<Protocoloelaboracion> protocoloelaboracions) {
		this.producto = producto;
		this.ffaViaAdministracion = ffaViaAdministracion;
		this.ffaTipoForma = ffaTipoForma;
		this.composicions = composicions;
		this.protocoloelaboracions = protocoloelaboracions;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "producto"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "proId", unique = true, nullable = false)
	public int getProId() {
		return this.proId;
	}

	public void setProId(int proId) {
		this.proId = proId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "ffaViaAdministracion", nullable = false, length = 45)
	public String getFfaViaAdministracion() {
		return this.ffaViaAdministracion;
	}

	public void setFfaViaAdministracion(String ffaViaAdministracion) {
		this.ffaViaAdministracion = ffaViaAdministracion;
	}

	@Column(name = "ffaTipoForma", nullable = false, length = 45)
	public String getFfaTipoForma() {
		return this.ffaTipoForma;
	}

	public void setFfaTipoForma(String ffaTipoForma) {
		this.ffaTipoForma = ffaTipoForma;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formafarmaceutica")
	public Set<Composicion> getComposicions() {
		return this.composicions;
	}

	public void setComposicions(Set<Composicion> composicions) {
		this.composicions = composicions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formafarmaceutica")
	public Set<Protocoloelaboracion> getProtocoloelaboracions() {
		return this.protocoloelaboracions;
	}

	public void setProtocoloelaboracions(Set<Protocoloelaboracion> protocoloelaboracions) {
		this.protocoloelaboracions = protocoloelaboracions;
	}

}
