package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Formula generated by hbm2java
 */
@Entity
@Table(name = "formula", catalog = "sifc_dev")
public class Formula implements java.io.Serializable {

	private Integer forId;
	private String forNombre;
	private String forDescripcion;
	public String ejemplo;
	private Set<Protocoloelaboracion> protocoloelaboracions = new HashSet<Protocoloelaboracion>(0);

	public Formula() {
	}

	public Formula(String forNombre, String forDescripcion) {
		this.forNombre = forNombre;
		this.forDescripcion = forDescripcion;
	}

	public Formula(String forNombre, String forDescripcion, Set<Protocoloelaboracion> protocoloelaboracions) {
		this.forNombre = forNombre;
		this.forDescripcion = forDescripcion;
		this.protocoloelaboracions = protocoloelaboracions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "forId", unique = true, nullable = false)
	public Integer getForId() {
		return this.forId;
	}

	public void setForId(Integer forId) {
		this.forId = forId;
	}

	@Column(name = "forNombre", nullable = false, length = 45)
	public String getForNombre() {
		return this.forNombre;
	}

	public void setForNombre(String forNombre) {
		this.forNombre = forNombre;
	}

	@Column(name = "forDescripcion", nullable = false, length = 65535)
	public String getForDescripcion() {
		return this.forDescripcion;
	}

	public void setForDescripcion(String forDescripcion) {
		this.forDescripcion = forDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formula")
	public Set<Protocoloelaboracion> getProtocoloelaboracions() {
		return this.protocoloelaboracions;
	}

	public void setProtocoloelaboracions(Set<Protocoloelaboracion> protocoloelaboracions) {
		this.protocoloelaboracions = protocoloelaboracions;
	}

}
