package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Imagenporproducto generated by hbm2java
 */
@Entity
@Table(name = "imagenporproducto", catalog = "sifc_dev")
public class Imagenporproducto implements java.io.Serializable {

	private Integer ipId;
	private Producto producto;
	private boolean ipEsPrincipal;
	private byte[] ipImagen;
	private String ipDescripcion;

	public Imagenporproducto() {
	}

	public Imagenporproducto(Producto producto, byte[] ipImagen) {
		this.producto = producto;
		this.ipImagen = ipImagen;
	}

	public Imagenporproducto(Producto producto, byte[] ipImagen, String ipDescripcion) {
		this.producto = producto;
		this.ipImagen = ipImagen;
		this.ipDescripcion = ipDescripcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ipId", unique = true, nullable = false)
	public Integer getIpId() {
		return this.ipId;
	}

	public void setIpId(Integer ipId) {
		this.ipId = ipId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ipProducto_proId", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "ipImagen", nullable = false)
	public byte[] getIpImagen() {
		return this.ipImagen;
	}

	public void setIpImagen(byte[] ipImagen) {
		this.ipImagen = ipImagen;
	}

	@Column(name = "ipDescripcion", length = 65535)
	public String getIpDescripcion() {
		return this.ipDescripcion;
	}

	public void setIpDescripcion(String ipDescripcion) {
		this.ipDescripcion = ipDescripcion;
	}

	@Column(name = "ipEsPrincipal", nullable = false)
	public boolean isIpEsPrincipal() {
		return this.ipEsPrincipal;
	}

	public void setIpEsPrincipal(boolean ipEsPrincipal) {
		this.ipEsPrincipal = ipEsPrincipal;
	}
}
