package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Imagenporenvase generated by hbm2java
 */
@Entity
@Table(name = "imagenporenvase", catalog = "sifc_dev")
public class Imagenporenvase implements java.io.Serializable {

	private Integer ipeId;
	private Envase envase;
	private byte[] ipeImagen;

	public Imagenporenvase() {
	}

	public Imagenporenvase(Envase envase, byte[] ipeImagen) {
		this.envase = envase;
		this.ipeImagen = ipeImagen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ipeId", unique = true, nullable = false)
	public Integer getIpeId() {
		return this.ipeId;
	}

	public void setIpeId(Integer ipeId) {
		this.ipeId = ipeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ipeEnvase_envId", nullable = false)
	public Envase getEnvase() {
		return this.envase;
	}

	public void setEnvase(Envase envase) {
		this.envase = envase;
	}

	@Column(name = "ipeImagen", nullable = false)
	public byte[] getIpeImagen() {
		return this.ipeImagen;
	}

	public void setIpeImagen(byte[] ipeImagen) {
		this.ipeImagen = ipeImagen;
	}

}
