package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Laboratorio generated by hbm2java
 */
@Entity
@Table(name = "laboratorio", catalog = "sifc_dev")
public class Laboratorio implements java.io.Serializable {

	private Integer labId;
	private String labNombre;
	private String labDireccion;
	private Set<Lote> lotes = new HashSet<Lote>(0);

	public Laboratorio() {
	}

	public Laboratorio(String labNombre, String labDireccion) {
		this.labNombre = labNombre;
		this.labDireccion = labDireccion;
	}

	public Laboratorio(String labNombre, String labDireccion, Set<Lote> lotes) {
		this.labNombre = labNombre;
		this.labDireccion = labDireccion;
		this.lotes = lotes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "labId", unique = true, nullable = false)
	public Integer getLabId() {
		return this.labId;
	}

	public void setLabId(Integer labId) {
		this.labId = labId;
	}

	@Column(name = "labNombre", nullable = false, length = 100)
	public String getLabNombre() {
		return this.labNombre;
	}

	public void setLabNombre(String labNombre) {
		this.labNombre = labNombre;
	}

	@Column(name = "labDireccion", nullable = false, length = 150)
	public String getLabDireccion() {
		return this.labDireccion;
	}

	public void setLabDireccion(String labDireccion) {
		this.labDireccion = labDireccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "laboratorio")
	public Set<Lote> getLotes() {
		return this.lotes;
	}

	public void setLotes(Set<Lote> lotes) {
		this.lotes = lotes;
	}

}
