package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LotehistoriaestadoId generated by hbm2java
 */
@Embeddable
public class LotehistoriaestadoId implements java.io.Serializable {

	private int lheId;
	private int lheLoteLotId;

	public LotehistoriaestadoId() {
	}

	public LotehistoriaestadoId(int lheId, int lheLoteLotId) {
		this.lheId = lheId;
		this.lheLoteLotId = lheLoteLotId;
	}

	@Column(name = "lheId", nullable = false)
	public int getLheId() {
		return this.lheId;
	}

	public void setLheId(int lheId) {
		this.lheId = lheId;
	}

	@Column(name = "lheLote_lotId", nullable = false)
	public int getLheLoteLotId() {
		return this.lheLoteLotId;
	}

	public void setLheLoteLotId(int lheLoteLotId) {
		this.lheLoteLotId = lheLoteLotId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LotehistoriaestadoId))
			return false;
		LotehistoriaestadoId castOther = (LotehistoriaestadoId) other;

		return (this.getLheId() == castOther.getLheId()) && (this.getLheLoteLotId() == castOther.getLheLoteLotId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLheId();
		result = 37 * result + this.getLheLoteLotId();
		return result;
	}

}
