package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lotemateriaprima generated by hbm2java
 */
@Entity
@Table(name = "lotemateriaprima", catalog = "sifc_dev")
public class Lotemateriaprima implements java.io.Serializable {

	private Integer lmpId;
	private Bodega bodega;
	private Materiaprima materiaprima;
	private String lmpNoLote;
	private String lmpEstado;
	private Date lmpFechaCaducidad;
	private Date lmpFechaRecepcion;
	private int lmpCantidad;
	private Set<Fichaanaliticamateria> fichaanaliticamaterias = new HashSet<Fichaanaliticamateria>(0);

	public Lotemateriaprima() {
	}

	public Lotemateriaprima(Bodega bodega, Materiaprima materiaprima, String lmpNoLote, String lmpEstado,
			Date lmpFechaCaducidad, Date lmpFechaRecepcion, int lmpCantidad) {
		this.bodega = bodega;
		this.materiaprima = materiaprima;
		this.lmpNoLote = lmpNoLote;
		this.lmpEstado = lmpEstado;
		this.lmpFechaCaducidad = lmpFechaCaducidad;
		this.lmpFechaRecepcion = lmpFechaRecepcion;
		this.lmpCantidad = lmpCantidad;
	}

	public Lotemateriaprima(Bodega bodega, Materiaprima materiaprima, String lmpNoLote, String lmpEstado,
			Date lmpFechaCaducidad, Date lmpFechaRecepcion, int lmpCantidad,
			Set<Fichaanaliticamateria> fichaanaliticamaterias) {
		this.bodega = bodega;
		this.materiaprima = materiaprima;
		this.lmpNoLote = lmpNoLote;
		this.lmpEstado = lmpEstado;
		this.lmpFechaCaducidad = lmpFechaCaducidad;
		this.lmpFechaRecepcion = lmpFechaRecepcion;
		this.lmpCantidad = lmpCantidad;
		this.fichaanaliticamaterias = fichaanaliticamaterias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "lmpId", unique = true, nullable = false)
	public Integer getLmpId() {
		return this.lmpId;
	}

	public void setLmpId(Integer lmpId) {
		this.lmpId = lmpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Bodega_boId", nullable = false)
	public Bodega getBodega() {
		return this.bodega;
	}

	public void setBodega(Bodega bodega) {
		this.bodega = bodega;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lmpMateriaPrima_mpId", nullable = false)
	public Materiaprima getMateriaprima() {
		return this.materiaprima;
	}

	public void setMateriaprima(Materiaprima materiaprima) {
		this.materiaprima = materiaprima;
	}

	@Column(name = "lmpNoLote", nullable = false, length = 45)
	public String getLmpNoLote() {
		return this.lmpNoLote;
	}

	public void setLmpNoLote(String lmpNoLote) {
		this.lmpNoLote = lmpNoLote;
	}

	@Column(name = "lmpEstado", nullable = false, length = 45)
	public String getLmpEstado() {
		return this.lmpEstado;
	}

	public void setLmpEstado(String lmpEstado) {
		this.lmpEstado = lmpEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lmpFechaCaducidad", nullable = false, length = 10)
	public Date getLmpFechaCaducidad() {
		return this.lmpFechaCaducidad;
	}

	public void setLmpFechaCaducidad(Date lmpFechaCaducidad) {
		this.lmpFechaCaducidad = lmpFechaCaducidad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lmpFechaRecepcion", nullable = false, length = 10)
	public Date getLmpFechaRecepcion() {
		return this.lmpFechaRecepcion;
	}

	public void setLmpFechaRecepcion(Date lmpFechaRecepcion) {
		this.lmpFechaRecepcion = lmpFechaRecepcion;
	}

	@Column(name = "lmpCantidad", nullable = false)
	public int getLmpCantidad() {
		return this.lmpCantidad;
	}

	public void setLmpCantidad(int lmpCantidad) {
		this.lmpCantidad = lmpCantidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lotemateriaprima")
	public Set<Fichaanaliticamateria> getFichaanaliticamaterias() {
		return this.fichaanaliticamaterias;
	}

	public void setFichaanaliticamaterias(Set<Fichaanaliticamateria> fichaanaliticamaterias) {
		this.fichaanaliticamaterias = fichaanaliticamaterias;
	}

}
