package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lote generated by hbm2java
 */
@Entity
@Table(name = "lote", catalog = "sifc_dev")
public class Lote implements java.io.Serializable {

	private Integer lotId;
	private Laboratorio laboratorio;
	private Producto producto;
	private Usuario usuario;
	private String lotNoLote;
	private int lotCantidad;
	private String lotEstado;
	private Date lotFechaVencimiento;
	private Set<Lotehistoriaestado> lotehistoriaestados = new HashSet<Lotehistoriaestado>(0);
	private Set<Fichaelaboracionproducto> fichaelaboracionproductos = new HashSet<Fichaelaboracionproducto>(0);

	public Lote() {
	}

	public Lote(Laboratorio laboratorio, Producto producto, Usuario usuario, String lotNoLote, int lotCantidad,
			String lotEstado, Date lotFechaVencimiento) {
		this.laboratorio = laboratorio;
		this.producto = producto;
		this.usuario = usuario;
		this.lotNoLote = lotNoLote;
		this.lotCantidad = lotCantidad;
		this.lotEstado = lotEstado;
		this.lotFechaVencimiento = lotFechaVencimiento;
	}

	public Lote(Laboratorio laboratorio, Producto producto, Usuario usuario, String lotNoLote, int lotCantidad,
			String lotEstado, Date lotFechaVencimiento, Set<Lotehistoriaestado> lotehistoriaestados,
			Set<Fichaelaboracionproducto> fichaelaboracionproductos) {
		this.laboratorio = laboratorio;
		this.producto = producto;
		this.usuario = usuario;
		this.lotNoLote = lotNoLote;
		this.lotCantidad = lotCantidad;
		this.lotEstado = lotEstado;
		this.lotFechaVencimiento = lotFechaVencimiento;
		this.lotehistoriaestados = lotehistoriaestados;
		this.fichaelaboracionproductos = fichaelaboracionproductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "lotId", unique = true, nullable = false)
	public Integer getLotId() {
		return this.lotId;
	}

	public void setLotId(Integer lotId) {
		this.lotId = lotId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lotLaboratorio_labId", nullable = false)
	public Laboratorio getLaboratorio() {
		return this.laboratorio;
	}

	public void setLaboratorio(Laboratorio laboratorio) {
		this.laboratorio = laboratorio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lotProducto_proId", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lotUsuario_usId", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "lotNoLote", nullable = false, length = 45)
	public String getLotNoLote() {
		return this.lotNoLote;
	}

	public void setLotNoLote(String lotNoLote) {
		this.lotNoLote = lotNoLote;
	}

	@Column(name = "lotCantidad", nullable = false)
	public int getLotCantidad() {
		return this.lotCantidad;
	}

	public void setLotCantidad(int lotCantidad) {
		this.lotCantidad = lotCantidad;
	}

	@Column(name = "lotEstado", nullable = false, length = 45)
	public String getLotEstado() {
		return this.lotEstado;
	}

	public void setLotEstado(String lotEstado) {
		this.lotEstado = lotEstado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lotFechaVencimiento", nullable = false, length = 26)
	public Date getLotFechaVencimiento() {
		return this.lotFechaVencimiento;
	}

	public void setLotFechaVencimiento(Date lotFechaVencimiento) {
		this.lotFechaVencimiento = lotFechaVencimiento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lote")
	public Set<Lotehistoriaestado> getLotehistoriaestados() {
		return this.lotehistoriaestados;
	}

	public void setLotehistoriaestados(Set<Lotehistoriaestado> lotehistoriaestados) {
		this.lotehistoriaestados = lotehistoriaestados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lote")
	public Set<Fichaelaboracionproducto> getFichaelaboracionproductos() {
		return this.fichaelaboracionproductos;
	}

	public void setFichaelaboracionproductos(Set<Fichaelaboracionproducto> fichaelaboracionproductos) {
		this.fichaelaboracionproductos = fichaelaboracionproductos;
	}

}
