package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Materiaprima generated by hbm2java
 */
@Entity
@Table(name = "materiaprima", catalog = "sifc_dev")
public class Materiaprima implements java.io.Serializable {
	private Integer mpId;
	private Tipomateriaprima tipomateriaprima;
	private Unidadmedida unidadmedida;
	private String mpNombre;
	private int mpContenido;
	private Date mpUltimaModificacion;
	private String mpCondicionConservacion;
	private String mpDescripcion;
	private int mpCantidad;
	private Set<Composicion> composicions = new HashSet<Composicion>(0);
	private Set<Movimientomateria> movimientomaterias = new HashSet<Movimientomateria>(0);
	private Set<Lotemateriaprima> lotemateriaprimas = new HashSet<Lotemateriaprima>(0);
	private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);

	public Materiaprima() {
	}

	public Materiaprima(Tipomateriaprima tipomateriaprima, Unidadmedida unidadmedida, String mpNombre, int mpContenido,
			Date mpUltimaModificacion, String mpCondicionConservacion) {
		this.tipomateriaprima = tipomateriaprima;
		this.unidadmedida = unidadmedida;
		this.mpNombre = mpNombre;
		this.mpContenido = mpContenido;
		this.mpUltimaModificacion = mpUltimaModificacion;
		this.mpCondicionConservacion = mpCondicionConservacion;
	}

	public Materiaprima(Tipomateriaprima tipomateriaprima, Unidadmedida unidadmedida, String mpNombre, int mpContenido,
			Date mpUltimaModificacion, String mpCondicionConservacion, Set<Composicion> composicions,
			Set<Movimientomateria> movimientomaterias, Set<Lotemateriaprima> lotemateriaprimas,
			Set<Proveedor> proveedors) {
		this.tipomateriaprima = tipomateriaprima;
		this.unidadmedida = unidadmedida;
		this.mpNombre = mpNombre;
		this.mpContenido = mpContenido;
		this.mpUltimaModificacion = mpUltimaModificacion;
		this.mpCondicionConservacion = mpCondicionConservacion;
		this.composicions = composicions;
		this.movimientomaterias = movimientomaterias;
		this.lotemateriaprimas = lotemateriaprimas;
		this.proveedors = proveedors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mpId", unique = true, nullable = false)
	public Integer getMpId() {
		return this.mpId;
	}

	public void setMpId(Integer mpId) {
		this.mpId = mpId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mpTipoMateriaProducto_tmpId", nullable = false)
	public Tipomateriaprima getTipomateriaprima() {
		return this.tipomateriaprima;
	}

	public void setTipomateriaprima(Tipomateriaprima tipomateriaprima) {
		this.tipomateriaprima = tipomateriaprima;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mpUnidadMedida_umId", nullable = false)
	public Unidadmedida getUnidadmedida() {
		return this.unidadmedida;
	}

	public void setUnidadmedida(Unidadmedida unidadmedida) {
		this.unidadmedida = unidadmedida;
	}

	@Column(name = "mpNombre", nullable = false, length = 100)
	public String getMpNombre() {
		return this.mpNombre;
	}

	public void setMpNombre(String mpNombre) {
		this.mpNombre = mpNombre;
	}

	@Column(name = "mpContenido", nullable = false)
	public int getMpContenido() {
		return this.mpContenido;
	}

	public void setMpContenido(int mpContenido) {
		this.mpContenido = mpContenido;
	}
	
	@Column(name = "mpCantidad", nullable = false)
	public int getMpCantidad() {
		return this.mpCantidad;
	}

	public void setMpCantidad(int mpCantidad) {
		this.mpCantidad = mpCantidad;
	}
	
	@Column(name = "mpDescripcion", nullable = false)
	public String getMpDescripcion() {
		return mpDescripcion;
	}

	public void setMpDescripcion(String mpDescripcion) {
		this.mpDescripcion = mpDescripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mpUltimaModificacion", nullable = false, length = 26)
	public Date getMpUltimaModificacion() {
		return this.mpUltimaModificacion;
	}

	public void setMpUltimaModificacion(Date mpUltimaModificacion) {
		this.mpUltimaModificacion = mpUltimaModificacion;
	}

	@Column(name = "mpCondicionConservacion", nullable = false, length = 65535)
	public String getMpCondicionConservacion() {
		return this.mpCondicionConservacion;
	}

	public void setMpCondicionConservacion(String mpCondicionConservacion) {
		this.mpCondicionConservacion = mpCondicionConservacion;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "materiaprima")
	public Set<Composicion> getComposicions() {
		return this.composicions;
	}

	public void setComposicions(Set<Composicion> composicions) {
		this.composicions = composicions;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "materiaprima")
	public Set<Movimientomateria> getMovimientomaterias() {
		return this.movimientomaterias;
	}

	public void setMovimientomaterias(Set<Movimientomateria> movimientomaterias) {
		this.movimientomaterias = movimientomaterias;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "materiaprima")
	public Set<Lotemateriaprima> getLotemateriaprimas() {
		return this.lotemateriaprimas;
	}

	public void setLotemateriaprimas(Set<Lotemateriaprima> lotemateriaprimas) {
		this.lotemateriaprimas = lotemateriaprimas;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "materiaporproveedor", catalog = "sifc_dev", joinColumns = {
			@JoinColumn(name = "mppMateriaPrima_mpId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "mppProveedor_prvId", nullable = false, updatable = false) })
	public Set<Proveedor> getProveedors() {
		return this.proveedors;
	}

	public void setProveedors(Set<Proveedor> proveedors) {
		this.proveedors = proveedors;
	}

}
