package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movimientoproducto generated by hbm2java
 */
@Entity
@Table(name = "movimientoproducto", catalog = "sifc_dev")
public class Movimientoproducto implements java.io.Serializable {

	private Integer mpId;
	private Producto producto;
	private Tipooperacion tipooperacion;
	private Usuario usuario;
	private Date mpFecha;
	private int mpCantidad;
	
	public Movimientoproducto() {
	}

	public Movimientoproducto(Producto producto, Tipooperacion tipooperacion, Usuario usuario, Date mpFecha) {
		this.producto = producto;
		this.tipooperacion = tipooperacion;
		this.usuario = usuario;
		this.mpFecha = mpFecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mpId", unique = true, nullable = false)
	public Integer getMpId() {
		return this.mpId;
	}

	public void setMpId(Integer mpId) {
		this.mpId = mpId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mpProducto_proId", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mpTipoOperacion_toId", nullable = false)
	public Tipooperacion getTipooperacion() {
		return this.tipooperacion;
	}

	public void setTipooperacion(Tipooperacion tipooperacion) {
		this.tipooperacion = tipooperacion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mpUsuario_usId", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mpFecha", nullable = false, length = 26)
	public Date getMpFecha() {
		return this.mpFecha;
	}

	public void setMpFecha(Date mpFecha) {
		this.mpFecha = mpFecha;
	}

	@Column(name = "mpCantidad", nullable = false)
	public int getMpCantidad() {
		return mpCantidad;
	}

	public void setMpCantidad(int mpCantidad) {
		this.mpCantidad = mpCantidad;
	}
	
	

}
