package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movimientomateria generated by hbm2java
 */
@Entity
@Table(name = "movimientomateria", catalog = "sifc_dev")
public class Movimientomateria implements java.io.Serializable {

	private Integer mmpId;
	private Materiaprima materiaprima;
	private Proveedor proveedor;
	private Tipooperacion tipooperacion;
	private Usuario usuario;
	private int mmpCantidad;
	private String mmpObservacion;
	private Date mmpFecha;

	public Movimientomateria() {
	}

	public Movimientomateria(Materiaprima materiaprima, Proveedor proveedor, Tipooperacion tipooperacion,
			Usuario usuario, int mmpCantidad, String mmpObservacion, Date mmpFecha) {
		this.materiaprima = materiaprima;
		this.proveedor = proveedor;
		this.tipooperacion = tipooperacion;
		this.usuario = usuario;
		this.mmpCantidad = mmpCantidad;
		this.mmpObservacion = mmpObservacion;
		this.mmpFecha = mmpFecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mmpId", unique = true, nullable = false)
	public Integer getMmpId() {
		return this.mmpId;
	}

	public void setMmpId(Integer mmpId) {
		this.mmpId = mmpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mmpMateriaPrima_mpId", nullable = false)
	public Materiaprima getMateriaprima() {
		return this.materiaprima;
	}

	public void setMateriaprima(Materiaprima materiaprima) {
		this.materiaprima = materiaprima;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mmpProveedor_prvId", nullable = false)
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mmpTipoOperacion_toId", nullable = false)
	public Tipooperacion getTipooperacion() {
		return this.tipooperacion;
	}

	public void setTipooperacion(Tipooperacion tipooperacion) {
		this.tipooperacion = tipooperacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mmpUsuario_usId", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "mmpCantidad", nullable = false)
	public int getMmpCantidad() {
		return this.mmpCantidad;
	}

	public void setMmpCantidad(int mmpCantidad) {
		this.mmpCantidad = mmpCantidad;
	}

	@Column(name = "mmpObservacion", nullable = false, length = 65535)
	public String getMmpObservacion() {
		return this.mmpObservacion;
	}

	public void setMmpObservacion(String mmpObservacion) {
		this.mmpObservacion = mmpObservacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mmpFecha", nullable = false, length = 26)
	public Date getMmpFecha() {
		return this.mmpFecha;
	}

	public void setMmpFecha(Date mmpFecha) {
		this.mmpFecha = mmpFecha;
	}

}
