package com.duopharma.models;
// Generated 25/02/2020 04:47:30 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "sifc_dev")
public class Pedido implements java.io.Serializable {

	private Integer pedId;
	private Usuario usuarioByPedClienteCliId;
	private Usuario usuarioByPedAutorizador;
	private Date pedFechaInicial;
	private String pedEstado;
	private Date pedFechaConclusion;
	private String pedDescripcion;
	private byte[] pedFirmaAutorizacion;
	private Set<Productosporpedido> productosporpedidos = new HashSet<Productosporpedido>(0);

	public Pedido() {
	}

	public Pedido(Usuario usuarioByPedClienteCliId, Usuario usuarioByPedAutorizador, Date pedFechaInicial,
			String pedEstado) {
		this.usuarioByPedClienteCliId = usuarioByPedClienteCliId;
		this.usuarioByPedAutorizador = usuarioByPedAutorizador;
		this.pedFechaInicial = pedFechaInicial;
		this.pedEstado = pedEstado;
	}

	public Pedido(Usuario usuarioByPedClienteCliId, Usuario usuarioByPedAutorizador, Date pedFechaInicial,
			String pedEstado, Date pedFechaConclusion, String pedDescripcion, byte[] pedFirmaAutorizacion) {
		this.usuarioByPedClienteCliId = usuarioByPedClienteCliId;
		this.usuarioByPedAutorizador = usuarioByPedAutorizador;
		this.pedFechaInicial = pedFechaInicial;
		this.pedEstado = pedEstado;
		this.pedFechaConclusion = pedFechaConclusion;
		this.pedDescripcion = pedDescripcion;
		this.pedFirmaAutorizacion = pedFirmaAutorizacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pedId", unique = true, nullable = false)
	public Integer getPedId() {
		return this.pedId;
	}

	public void setPedId(Integer pedId) {
		this.pedId = pedId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pedCliente_cliId", nullable = false)
	public Usuario getUsuarioByPedClienteCliId() {
		return this.usuarioByPedClienteCliId;
	}

	public void setUsuarioByPedClienteCliId(Usuario usuarioByPedClienteCliId) {
		this.usuarioByPedClienteCliId = usuarioByPedClienteCliId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pedAutorizador", nullable = false)
	public Usuario getUsuarioByPedAutorizador() {
		return this.usuarioByPedAutorizador;
	}

	public void setUsuarioByPedAutorizador(Usuario usuarioByPedAutorizador) {
		this.usuarioByPedAutorizador = usuarioByPedAutorizador;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pedFechaInicial", nullable = false, length = 10)
	public Date getPedFechaInicial() {
		return this.pedFechaInicial;
	}

	public void setPedFechaInicial(Date pedFechaInicial) {
		this.pedFechaInicial = pedFechaInicial;
	}

	@Column(name = "pedEstado", nullable = false, length = 45)
	public String getPedEstado() {
		return this.pedEstado;
	}

	public void setPedEstado(String pedEstado) {
		this.pedEstado = pedEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pedFechaConclusion", length = 10)
	public Date getPedFechaConclusion() {
		return this.pedFechaConclusion;
	}

	public void setPedFechaConclusion(Date pedFechaConclusion) {
		this.pedFechaConclusion = pedFechaConclusion;
	}

	@Column(name = "pedDescripcion", length = 45)
	public String getPedDescripcion() {
		return this.pedDescripcion;
	}

	public void setPedDescripcion(String pedDescripcion) {
		this.pedDescripcion = pedDescripcion;
	}

	@Column(name = "pedFirmaAutorizacion")
	public byte[] getPedFirmaAutorizacion() {
		return this.pedFirmaAutorizacion;
	}

	public void setPedFirmaAutorizacion(byte[] pedFirmaAutorizacion) {
		this.pedFirmaAutorizacion = pedFirmaAutorizacion;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "pedido")
	public Set<Productosporpedido> getProductosporpedidos() {
		return this.productosporpedidos;
	}

	public void setProductosporpedidos(Set<Productosporpedido> productosporpedidos) {
		this.productosporpedidos = productosporpedidos;
	}

}
