package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductosporpedidoId generated by hbm2java
 */
@Embeddable
public class ProductosporpedidoId implements java.io.Serializable {

	private int prpPedidoPedId;
	private int prpProductoProId;

	public ProductosporpedidoId() {
	}

	public ProductosporpedidoId(int prpPedidoPedId, int prpProductoProId) {
		this.prpPedidoPedId = prpPedidoPedId;
		this.prpProductoProId = prpProductoProId;
	}

	@Column(name = "prpPedido_pedId", nullable = false)
	public int getPrpPedidoPedId() {
		return this.prpPedidoPedId;
	}

	public void setPrpPedidoPedId(int prpPedidoPedId) {
		this.prpPedidoPedId = prpPedidoPedId;
	}

	@Column(name = "prpProducto_proId", nullable = false)
	public int getPrpProductoProId() {
		return this.prpProductoProId;
	}

	public void setPrpProductoProId(int prpProductoProId) {
		this.prpProductoProId = prpProductoProId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductosporpedidoId))
			return false;
		ProductosporpedidoId castOther = (ProductosporpedidoId) other;

		return (this.getPrpPedidoPedId() == castOther.getPrpPedidoPedId())
				&& (this.getPrpProductoProId() == castOther.getPrpProductoProId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPrpPedidoPedId();
		result = 37 * result + this.getPrpProductoProId();
		return result;
	}

}
