package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productosporpedido generated by hbm2java
 */
@Entity
@Table(name = "productosporpedido", catalog = "sifc_dev")
public class Productosporpedido implements java.io.Serializable {

	private ProductosporpedidoId id;
	private Pedido pedido;
	private Producto producto;
	private int prpCantidad;

	public Productosporpedido() {
	}

	public Productosporpedido(ProductosporpedidoId id, Pedido pedido, Producto producto, int prpCantidad) {
		this.id = id;
		this.pedido = pedido;
		this.producto = producto;
		this.prpCantidad = prpCantidad;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "prpPedidoPedId", column = @Column(name = "prpPedido_pedId", nullable = false)),
			@AttributeOverride(name = "prpProductoProId", column = @Column(name = "prpProducto_proId", nullable = false)) })
	public ProductosporpedidoId getId() {
		return this.id;
	}

	public void setId(ProductosporpedidoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prpPedido_pedId", nullable = false, insertable = false, updatable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "prpProducto_proId", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "prpCantidad", nullable = false)
	public int getPrpCantidad() {
		return this.prpCantidad;
	}

	public void setPrpCantidad(int prpCantidad) {
		this.prpCantidad = prpCantidad;
	}

}
