package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Protocoloelaboracion generated by hbm2java
 */
@Entity
@Table(name = "protocoloelaboracion", catalog = "sifc_dev")
public class Protocoloelaboracion implements java.io.Serializable {

	private Integer preId;
	private Envase envase;
	private Formafarmaceutica formafarmaceutica;
	private Formula formula;
	private String preCodigo;

	public Protocoloelaboracion() {
	}

	public Protocoloelaboracion(Envase envase, Formafarmaceutica formafarmaceutica, Formula formula, String preCodigo) {
		this.envase = envase;
		this.formafarmaceutica = formafarmaceutica;
		this.formula = formula;
		this.preCodigo = preCodigo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "preId", unique = true, nullable = false)
	public Integer getPreId() {
		return this.preId;
	}

	public void setPreId(Integer preId) {
		this.preId = preId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "preEnvase_envId", nullable = false)
	public Envase getEnvase() {
		return this.envase;
	}

	public void setEnvase(Envase envase) {
		this.envase = envase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "preFormaFarmaceutica_proId", nullable = false)
	public Formafarmaceutica getFormafarmaceutica() {
		return this.formafarmaceutica;
	}

	public void setFormafarmaceutica(Formafarmaceutica formafarmaceutica) {
		this.formafarmaceutica = formafarmaceutica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "preFormula_forId", nullable = false)
	public Formula getFormula() {
		return this.formula;
	}

	public void setFormula(Formula formula) {
		this.formula = formula;
	}

	@Column(name = "preCodigo", nullable = false, length = 45)
	public String getPreCodigo() {
		return this.preCodigo;
	}

	public void setPreCodigo(String preCodigo) {
		this.preCodigo = preCodigo;
	}

}
