package com.duopharma.models;
// Generated 25/02/2020 04:47:30 PM by Hibernate Tools 4.3.5.Final
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name = "proveedor", catalog = "sifc_dev")
public class Proveedor implements java.io.Serializable {

	private Integer prvId;
	private String prvNombre;
	private String prvDireccion;
	private long prvNumeroContacto;
	private String prvCorreo;
	private String prvDescripcion;
	private boolean prvEstado;
	private Set<Materiaprima> materiaprimas = new HashSet<Materiaprima>(0);
	private Set<Envase> envases = new HashSet<Envase>(0);
	private Set<Movimientomateria> movimientomaterias = new HashSet<Movimientomateria>(0);
	
	public Proveedor() {
	}

	public Proveedor(String prvNombre, String prvDireccion, int prvNumeroContacto, String prvCorreo,
			boolean prvEstado) {
		this.prvNombre = prvNombre;
		this.prvDireccion = prvDireccion;
		this.prvNumeroContacto = prvNumeroContacto;
		this.prvCorreo = prvCorreo;
		this.prvEstado = prvEstado;
	}

	public Proveedor(String prvNombre, String prvDireccion, int prvNumeroContacto, String prvCorreo,
			String prvDescripcion, boolean prvEstado) {
		this.prvNombre = prvNombre;
		this.prvDireccion = prvDireccion;
		this.prvNumeroContacto = prvNumeroContacto;
		this.prvCorreo = prvCorreo;
		this.prvDescripcion = prvDescripcion;
		this.prvEstado = prvEstado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "prvId", unique = true, nullable = false)
	public Integer getPrvId() {
		return this.prvId;
	}

	public void setPrvId(Integer prvId) {
		this.prvId = prvId;
	}

	@Column(name = "prvNombre", nullable = false, length = 50)
	public String getPrvNombre() {
		return this.prvNombre;
	}

	public void setPrvNombre(String prvNombre) {
		this.prvNombre = prvNombre;
	}

	@Column(name = "prvDireccion", nullable = false, length = 50)
	public String getPrvDireccion() {
		return this.prvDireccion;
	}

	public void setPrvDireccion(String prvDireccion) {
		this.prvDireccion = prvDireccion;
	}

	@Column(name = "prvNumeroContacto", nullable = false)
	public long getPrvNumeroContacto() {
		return this.prvNumeroContacto;
	}

	public void setPrvNumeroContacto(long prvNumeroContacto) {
		this.prvNumeroContacto = prvNumeroContacto;
	}

	@Column(name = "prvCorreo", nullable = false, length = 90)
	public String getPrvCorreo() {
		return this.prvCorreo;
	}

	public void setPrvCorreo(String prvCorreo) {
		this.prvCorreo = prvCorreo;
	}

	@Column(name = "prvDescripcion", length = 65535)
	public String getPrvDescripcion() {
		return this.prvDescripcion;
	}

	public void setPrvDescripcion(String prvDescripcion) {
		this.prvDescripcion = prvDescripcion;
	}

	@Column(name = "prvEstado", nullable = false)
	public boolean isPrvEstado() {
		return this.prvEstado;
	}

	public void setPrvEstado(boolean prvEstado) {
		this.prvEstado = prvEstado;
	}
	
	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "materiaporproveedor", catalog = "sifc_dev", joinColumns = {
			@JoinColumn(name = "mppProveedor_prvId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "mppMateriaPrima_mpId", nullable = false, updatable = false) })
	public Set<Materiaprima> getMateriaprimas() {
		return this.materiaprimas;
	}

	public void setMateriaprimas(Set<Materiaprima> materiaprimas) {
		this.materiaprimas = materiaprimas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<Envase> getEnvases() {
		return this.envases;
	}

	public void setEnvases(Set<Envase> envases) {
		this.envases = envases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<Movimientomateria> getMovimientomaterias() {
		return this.movimientomaterias;
	}

	public void setMovimientomaterias(Set<Movimientomateria> movimientomaterias) {
		this.movimientomaterias = movimientomaterias;
	}

}
