package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipomateriaprima generated by hbm2java
 */
@Entity
@Table(name = "tipomateriaprima", catalog = "sifc_dev")
public class Tipomateriaprima implements java.io.Serializable {

	private Integer tmpId;
	private String tmpNombre;
	private String tmpDescripcion;
	private Set<Materiaprima> materiaprimas = new HashSet<Materiaprima>(0);

	public Tipomateriaprima() {
	}

	public Tipomateriaprima(String tmpNombre) {
		this.tmpNombre = tmpNombre;
	}

	public Tipomateriaprima(String tmpNombre, String tmpDescripcion, Set<Materiaprima> materiaprimas) {
		this.tmpNombre = tmpNombre;
		this.tmpDescripcion = tmpDescripcion;
		this.materiaprimas = materiaprimas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tmpId", unique = true, nullable = false)
	public Integer getTmpId() {
		return this.tmpId;
	}

	public void setTmpId(Integer tmpId) {
		this.tmpId = tmpId;
	}

	@Column(name = "tmpNombre", nullable = false, length = 50)
	public String getTmpNombre() {
		return this.tmpNombre;
	}

	public void setTmpNombre(String tmpNombre) {
		this.tmpNombre = tmpNombre;
	}

	@Column(name = "tmpDescripcion", length = 65535)
	public String getTmpDescripcion() {
		return this.tmpDescripcion;
	}

	public void setTmpDescripcion(String tmpDescripcion) {
		this.tmpDescripcion = tmpDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipomateriaprima")
	public Set<Materiaprima> getMateriaprimas() {
		return this.materiaprimas;
	}

	public void setMateriaprimas(Set<Materiaprima> materiaprimas) {
		this.materiaprimas = materiaprimas;
	}

}
