package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipodocumento generated by hbm2java
 */
@Entity
@Table(name = "tipodocumento", catalog = "sifc_dev")
public class Tipodocumento implements java.io.Serializable {

	private Integer tdId;
	private String tdNombre;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Tipodocumento() {
	}

	public Tipodocumento(String tdNombre) {
		this.tdNombre = tdNombre;
	}

	public Tipodocumento(String tdNombre, Set<Cliente> clientes, Set<Usuario> usuarios) {
		this.tdNombre = tdNombre;
		this.clientes = clientes;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tdId", unique = true, nullable = false)
	public Integer getTdId() {
		return this.tdId;
	}

	public void setTdId(Integer tdId) {
		this.tdId = tdId;
	}

	@Column(name = "tdNombre", nullable = false, length = 50)
	public String getTdNombre() {
		return this.tdNombre;
	}

	public void setTdNombre(String tdNombre) {
		this.tdNombre = tdNombre;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tipodocumento")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
