package com.duopharma.models;
// Generated 6/02/2020 04:23:00 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unidadmedida generated by hbm2java
 */
@Entity
@Table(name = "unidadmedida", catalog = "sifc_dev")
public class Unidadmedida implements java.io.Serializable {

	private Integer umId;
	private String umNombre;
	private String umAbreviacion;
	private Set<Producto> productos = new HashSet<Producto>(0);
	private Set<Materiaprima> materiaprimas = new HashSet<Materiaprima>(0);

	public Unidadmedida() {
	}

	public Unidadmedida(String umNombre, String umAbreviacion) {
		this.umNombre = umNombre;
		this.umAbreviacion = umAbreviacion;
	}

	public Unidadmedida(String umNombre, String umAbreviacion, Set<Producto> productos,
			Set<Materiaprima> materiaprimas) {
		this.umNombre = umNombre;
		this.umAbreviacion = umAbreviacion;
		this.productos = productos;
		this.materiaprimas = materiaprimas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "umId", unique = true, nullable = false)
	public Integer getUmId() {
		return this.umId;
	}

	public void setUmId(Integer umId) {
		this.umId = umId;
	}

	@Column(name = "umNombre", nullable = false, length = 50)
	public String getUmNombre() {
		return this.umNombre;
	}

	public void setUmNombre(String umNombre) {
		this.umNombre = umNombre;
	}

	@Column(name = "umAbreviacion", nullable = false, length = 5)
	public String getUmAbreviacion() {
		return this.umAbreviacion;
	}

	public void setUmAbreviacion(String umAbreviacion) {
		this.umAbreviacion = umAbreviacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadmedida")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadmedida")
	public Set<Materiaprima> getMateriaprimas() {
		return this.materiaprimas;
	}

	public void setMateriaprimas(Set<Materiaprima> materiaprimas) {
		this.materiaprimas = materiaprimas;
	}

}
