package com.duopharma.models;
// Generated 8/10/2019 09:13:20 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VistaproductoId generated by hbm2java
 */
@Entity
public class Vistaestanteriacapacidad implements java.io.Serializable {

	private Integer estId;
	private int estCapacidad;
	private int estCapacidadOcupada;
	
	private String boDireccion;
	private BigDecimal porcentajeOcupado;
	private BigDecimal porcentajeRestante;
	
	public Vistaestanteriacapacidad() {
	}
	
	@Id
	@Column(name = "estId")
	public Integer getEstId() {
		return estId;
	}
	
	public void setEstId(Integer estId) {
		this.estId = estId;
	}
	
	@Column(name = "estCapacidad")
	public int getEstCapacidad() {
		return estCapacidad;
	}

	public void setEstCapacidad(int estCapacidad) {
		this.estCapacidad = estCapacidad;
	}

	@Column(name = "estCapacidadOcupada")
	public int getEstCapacidadOcupada() {
		return estCapacidadOcupada;
	}

	public void setEstCapacidadOcupada(int estCapacidadOcupada) {
		this.estCapacidadOcupada = estCapacidadOcupada;
	}

	@Column(name = "boDireccion")
	public String getBoDireccion() {
		return boDireccion;
	}
	
	public void setBoDireccion(String boDireccion) {
		this.boDireccion = boDireccion;
	}

	@Column(name = "porcentajeOcupado")
	public BigDecimal getPorcentajeOcupado() {
		return porcentajeOcupado;
	}

	public void setPorcentajeOcupado(BigDecimal porcentajeOcupado) {
		this.porcentajeOcupado = porcentajeOcupado;
	}

	@Column(name = "porcentajeRestante")
	public BigDecimal getPorcentajeRestante() {
		return porcentajeRestante;
	}

	public void setPorcentajeRestante(BigDecimal porcentajeRestante) {
		this.porcentajeRestante = porcentajeRestante;
	}
}
