package com.duopharma.models;
// Generated 8/10/2019 09:13:20 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * VistaproductoId generated by hbm2java
 */
@Entity
@Table (name = "vistamateriaprima", catalog = "sifc_dev")
public class Vistamateriaprima implements java.io.Serializable {

	private Integer mpId;
	private String mpNombre;
	private int mpCantidad;
	private Date mpUltimaModificacion;

	private Integer umId;
	private String umNombre;
	private Integer tmpId;
	private String tmpNombre;
	
	@Id
	@Column (name = "mpId")
	public Integer getMpId() {
		return mpId;
	}
	
	public void setMpId(Integer mpId) {
		this.mpId = mpId;
	}
	
	@Column (name = "mpNombre")
	public String getMpNombre() {
		return mpNombre;
	}

	public void setMpNombre(String mpNombre) {
		this.mpNombre = mpNombre;
	}

	@Column (name = "mpCantidad")
	public int getMpCantidad() {
		return mpCantidad;
	}

	public void setMpCantidad(int mpCantidad) {
		this.mpCantidad = mpCantidad;
	}

	@Column (name = "mpUltimaModificacion")
	public Date getMpUltimaModificacion() {
		return mpUltimaModificacion;
	}

	public void setMpUltimaModificacion(Date mpUltimaModificacion) {
		this.mpUltimaModificacion = mpUltimaModificacion;
	}

	@Column (name = "umId")
	public Integer getUmId() {
		return umId;
	}

	public void setUmId(Integer umId) {
		this.umId = umId;
	}

	@Column (name = "tmpId")
	public Integer getTmpId() {
		return tmpId;
	}

	public void setTmpId(Integer tmpId) {
		this.tmpId = tmpId;
	}

	public Vistamateriaprima() {	
	}
	
	@Column (name ="umNombre")
	public String getUmNombre() {
		return umNombre;
	}

	public void setUmNombre(String umNombre) {
		this.umNombre = umNombre;
	}

	@Column (name = "tmpNombre")
	public String getTmpNombre() {
		return tmpNombre;
	}

	public void setTmpNombre(String tmpNombre) {
		this.tmpNombre = tmpNombre;
	}
	
}
