package com.duopharma.models;
// Generated 8/10/2019 09:13:20 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VistaproductoId generated by hbm2java
 */
@Entity
public class Vistaestanteria implements java.io.Serializable {

	private Integer estId;
	private int estCapacidad;
	private int estCapacidadOcupada;
	private String estEstado;
	
	private Integer boId;
	private String boDireccion;
	
	private Integer proId;
	private String proNombre;
	
	public Vistaestanteria() {
	}
	
	@Id
	@Column(name = "estId")
	public Integer getEstId() {
		return estId;
	}

	
	public void setEstId(Integer estId) {
		this.estId = estId;
	}
	
	@Column(name = "estCapacidad")
	public int getEstCapacidad() {
		return estCapacidad;
	}

	public void setEstCapacidad(int estCapacidad) {
		this.estCapacidad = estCapacidad;
	}

	@Column(name = "estCapacidadOcupada")
	public int getEstCapacidadOcupada() {
		return estCapacidadOcupada;
	}

	public void setEstCapacidadOcupada(int estCapacidadOcupada) {
		this.estCapacidadOcupada = estCapacidadOcupada;
	}

	@Column(name = "estEstado")
	public String getEstEstado() {
		return estEstado;
	}

	public void setEstEstado(String estEstado) {
		this.estEstado = estEstado;
	}
	
	@Column(name = "boId")
	public Integer getBoId() {
		return boId;
	}

	public void setBoId(Integer boId) {
		this.boId = boId;
	}

	@Column(name = "boDireccion")
	public String getBoDireccion() {
		return boDireccion;
	}
	
	public void setBoDireccion(String boDireccion) {
		this.boDireccion = boDireccion;
	}
	
	@Column(name = "proId")
	public Integer getProId() {
		return proId;
	}

	public void setProId(Integer proId) {
		this.proId = proId;
	}
	
	@Column(name = "proNombre")
	public String getProNombre() {
		return proNombre;
	}

	public void setProNombre(String proNombre) {
		this.proNombre = proNombre;
	}
}
