package com.duopharma.models;
// Generated 6/12/2019 10:24:50 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

/**
 * Vistausuario generated by hbm2java
 */
@Entity
public class Vistausuario implements java.io.Serializable {

	private int usId;
	private String usNombreDeUsuario;
	private String usClave;
	private String usCorreo;
	private String usNombres;
	private String usApellidos;
	private String usModificador;
	private Date usFechaCreacion;
	private Date usUltimaActualizacion;
	private String usActualizador;
	private byte[] usImagen;
	private String usEstado;
	private String usDireccion;
	private String rolNombre;
	private String boDireccion;
	private String tdNombre;
	
	private Integer rolId;
	private Integer boId;
	private Integer tdId;
	
	private String usDocumento;
	private Long usTelefono;
	
	public Vistausuario(){
		
	}
	
	@Id
	@Column(name = "usId", nullable = false)
	public int getUsId() {
		return this.usId;
	}

	public void setUsId(int usId) {
		this.usId = usId;
	}

	@Column(name = "usNombreDeUsuario", nullable = false, length = 50)
	public String getUsNombreDeUsuario() {
		return this.usNombreDeUsuario;
	}

	public void setUsNombreDeUsuario(String usNombreDeUsuario) {
		this.usNombreDeUsuario = usNombreDeUsuario;
	}

	@Column(name = "usClave", nullable = false, length = 50)
	public String getUsClave() {
		return this.usClave;
	}

	public void setUsClave(String usClave) {
		this.usClave = usClave;
	}

	@Column(name = "usCorreo", nullable = false, length = 90)
	public String getUsCorreo() {
		return this.usCorreo;
	}

	public void setUsCorreo(String usCorreo) {
		this.usCorreo = usCorreo;
	}

	@Column(name = "usNombres", nullable = false, length = 60)
	public String getUsNombres() {
		return this.usNombres;
	}

	public void setUsNombres(String usNombres) {
		this.usNombres = usNombres;
	}

	@Column(name = "usApellidos", nullable = false, length = 60)
	public String getUsApellidos() {
		return this.usApellidos;
	}

	public void setUsApellidos(String usApellidos) {
		this.usApellidos = usApellidos;
	}

	@Column(name = "usModificador", length = 50)
	public String getUsModificador() {
		return this.usModificador;
	}

	public void setUsModificador(String usModificador) {
		this.usModificador = usModificador;
	}

	@Column(name = "usFechaCreacion", nullable = false, length = 26)
	public Date getUsFechaCreacion() {
		return this.usFechaCreacion;
	}

	public void setUsFechaCreacion(Date usFechaCreacion) {
		this.usFechaCreacion = usFechaCreacion;
	}

	@Column(name = "usUltimaActualizacion", length = 26)
	public Date getUsUltimaActualizacion() {
		return this.usUltimaActualizacion;
	}

	public void setUsUltimaActualizacion(Date usUltimaActualizacion) {
		this.usUltimaActualizacion = usUltimaActualizacion;
	}

	@Column(name = "usActualizador", length = 50)
	public String getUsActualizador() {
		return this.usActualizador;
	}

	public void setUsActualizador(String usActualizador) {
		this.usActualizador = usActualizador;
	}
	@Lob @Basic(fetch = FetchType.EAGER)
	@Column(name = "usImagen", columnDefinition="BLOB NULL")
	public byte[] getUsImagen() {
		return this.usImagen;
	}

	public void setUsImagen(byte[] usImagen) {
		this.usImagen = usImagen;
	}

	@Column(name = "usEstado", length = 50)
	public String getUsEstado() {
		return this.usEstado;
	}

	public void setUsEstado(String usEstado) {
		this.usEstado = usEstado;
	}

	@Column(name = "usDireccion", length = 200)
	public String getUsDireccion() {
		return this.usDireccion;
	}

	public void setUsDireccion(String usDireccion) {
		this.usDireccion = usDireccion;
	}

	@Column(name = "rolNombre", length = 45)
	public String getRolNombre() {
		return this.rolNombre;
	}

	public void setRolNombre(String rolNombre) {
		this.rolNombre = rolNombre;
	}

	@Column(name = "boDireccion", length = 65535)
	public String getBoDireccion() {
		return this.boDireccion;
	}

	public void setBoDireccion(String boDireccion) {
		this.boDireccion = boDireccion;
	}

	@Column(name = "tdNombre", length = 50)
	public String getTdNombre() {
		return this.tdNombre;
	}

	public void setTdNombre(String tdNombre) {
		this.tdNombre = tdNombre;
	}

	@Column(name = "rolId")
	public Integer getRolId() {
		return rolId;
	}

	public void setRolId(Integer rolId) {
		this.rolId = rolId;
	}

	@Column(name = "boId")
	public Integer getBoId() {
		return boId;
	}

	public void setBoId(Integer boId) {
		this.boId = boId;
	}

	@Column(name = "tdId")
	public Integer getTdId() {
		return tdId;
	}

	public void setTdId(Integer tdId) {
		this.tdId = tdId;
	}

	@Column(name = "usDocumento")
	public String getUsDocumento() {
		return usDocumento;
	}

	public void setUsDocumento(String usDocumento) {
		this.usDocumento = usDocumento;
	}

	@Column(name = "usTelefono")
	public Long getUsTelefono() {
		return usTelefono;
	}

	public void setUsTelefono(Long usTelefono) {
		this.usTelefono = usTelefono;
	}
	
	
	
}
